apiVersion: apps/v1
kind: Deployment
metadata:
  name: cause
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cause
  template:
    metadata:
      labels:
        app: cause
    spec:
      containers:
      - image: okteto.dev/cause:latest
        name: cause
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.anime1st.com"
        - name: Vless_UUID
          value: "b02adf74-46a2-4f3f-8c1b-bb11850bfe86"
        - name: Vless_Path
          value: "/DACev6hyt"
        - name: Vmess_UUID
          value: "b02adf74-46a2-4f3f-8c1b-bb11850bfe86"
        - name: Vmess_Path
          value: "/ouietc14"
        - name: Share_Path
          value: "/Share311"
