apiVersion: apps/v1
kind: Deployment
metadata:
  name: docter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docter
  template:
    metadata:
      labels:
        app: docter
    spec:
      containers:
      - image: okteto.dev/docter:latest
        name: docter
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.plex.tv"
        - name: Vless_UUID
          value: "dda14282-401d-42b9-a3a7-19355076a373"
        - name: Vless_Path
          value: "/DHe6h34y"
        - name: Vmess_UUID
          value: "dda14282-401d-42b9-a3a7-19355076a373"
        - name: Vmess_Path
          value: "/gt6srytd"
        - name: Share_Path
          value: "/Share547"
