apiVersion: apps/v1
kind: Deployment
metadata:
  name: liyec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liyec
  template:
    metadata:
      labels:
        app: liyec
    spec:
      containers:
      - image: okteto.dev/liyec:latest
        name: liyec
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.plex.tv"
        - name: Vless_UUID
          value: "7b298dea-c604-4426-8ea1-09801c97ff8d"
        - name: Vless_Path
          value: "/oastcvb"
        - name: Vmess_UUID
          value: "7b298dea-c604-4426-8ea1-09801c97ff8d"
        - name: Vmess_Path
          value: "/likfdf"
        - name: Share_Path
          value: "/Share547"
