apiVersion: apps/v1
kind: Deployment
metadata:
  name: greact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greact
  template:
    metadata:
      labels:
        app: greact
    spec:
      containers:
      - image: okteto.dev/greact:latest
        name: greact
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "moviesjoy.to"
        - name: Vless_UUID
          value: "96b0cc3d-37d7-4495-a008-ccb5ceca877b"
        - name: Vless_Path
          value: "/ytAT7YIK"
        - name: Vmess_UUID
          value: "96b0cc3d-37d7-4495-a008-ccb5ceca877b"
        - name: Vmess_Path
          value: "/huiekth4r"
        - name: Share_Path
          value: "/Share443"
