apiVersion: apps/v1
kind: Deployment
metadata:
  name: uenow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uenow
  template:
    metadata:
      labels:
        app: uenow
    spec:
      containers:
      - image: okteto.dev/uenow:latest
        name: uenow
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.azmovies.net"
        - name: Vless_UUID
          value: "ad71bcb9-729d-4c56-9965-22d5bc48327e"
        - name: Vless_Path
          value: "/dfYRYT57"
        - name: Vmess_UUID
          value: "ad71bcb9-729d-4c56-9965-22d5bc48327e"
        - name: Vmess_Path
          value: "/ERr5ui4ty"
        - name: Share_Path
          value: "/Share034"
