apiVersion: apps/v1
kind: Deployment
metadata:
  name: dancing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dancing
  template:
    metadata:
      labels:
        app: dancing
    spec:
      containers:
      - image: okteto.dev/dancing:latest
        name: dancing
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.anime-planet.com"
        - name: Vless_UUID
          value: "0c0c2234-8ecd-4d01-8893-62672ce44615"
        - name: Vless_Path
          value: "/Grebe43"
        - name: Vmess_UUID
          value: "0c0c2234-8ecd-4d01-8893-62672ce44615"
        - name: Vmess_Path
          value: "/seachew"
        - name: Share_Path
          value: "/Share831"
